[package]
name = "poac-demo"
version = "0.1.0"
authors = []
edition = 2020

[dependencies]
"fmt" = {version = "9.1.0", registry = "conan-v1"}
"spdlog" = {version = "1.10.0", registry = "conan-v1"}
"leveldb" = {version = "1.23", registry = "conan-v1"}
